site_name: CCLHM063 - O mundo atlântico
site_url: https://ericbrasiln.github.io/cclhm0063

theme:
  #logo: img/banner.png
  favicon: img/logohist.png
  name: material 
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Mudar para modo noturno
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Mudar para modo claro


repo_url: https://github.com/ericbrasiln/cclhm0063
repo_name: ericbrasiln/cclhm0063

plugins:
  - git-revision-date

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.highlight
  - pymdownx.superfences
  - footnotes

nav:
    - Programa: index.md
    - Cronograma: cronograma.md
    - Guia de boas práticas: praticas.md
    - Leituras e atividades: leituras.md
    - Tarefas: tarefas.md
    - Contato: contatos.md
    - Licença: license.md 

